name: Android CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradle/wrapper/gradlew || true
      - name: Build with Gradle
        run: ./gradle/wrapper/gradlew build
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
